.TH "Dokumentacja katalogu /home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu /home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src \- 
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBCPU\&.cpp\fP"
.br
.RI "\fIDefinicja metody klasy \fBCPU\fP\&. \fP"
.ti -1c
.RI "plik \fBGRA\&.cpp\fP"
.br
.RI "\fIDefinicja metody klasy \fBGRA\fP\&. \fP"
.ti -1c
.RI "plik \fBgracz\&.cpp\fP"
.br
.RI "\fIDefinicja metody klasy \fBGracz\fP\&. \fP"
.ti -1c
.RI "plik \fBinterfejs\&.cpp\fP"
.br
.RI "\fIDefinicja metody klasy \fBInterfejs\fP\&. \fP"
.ti -1c
.RI "plik \fBkarta\&.cpp\fP"
.br
.RI "\fIDefinicja metody klasy \fBKarta\fP\&. \fP"
.ti -1c
.RI "plik \fBmain\&.cpp\fP"
.br
.RI "\fIPlik glowny programu\&. \fP"
.ti -1c
.RI "plik \fBtalia\&.cpp\fP"
.br
.RI "\fIDefinicja metody klasy \fBTalia\fP\&. \fP"
.ti -1c
.RI "plik \fBzestaw\&.cpp\fP"
.br
.RI "\fIDefinicja metody klasy \fBZestaw\fP\&. \fP"
.in -1c
