.TH "Dokumentacja katalogu /home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/inc" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu /home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/inc \- 
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBCPU\&.h\fP"
.br
.RI "\fIDefinicja klasy \fBCPU\fP\&. \fP"
.ti -1c
.RI "plik \fBGRA\&.h\fP"
.br
.RI "\fIDefinicja klasy \fBGRA\fP\&. \fP"
.ti -1c
.RI "plik \fBgracz\&.h\fP"
.br
.RI "\fIDefinicja klasy \fBGracz\fP\&. \fP"
.ti -1c
.RI "plik \fBinterfejs\&.h\fP"
.br
.RI "\fIDefinicja klasy \fBInterfejs\fP\&. \fP"
.ti -1c
.RI "plik \fBkarta\&.h\fP"
.br
.RI "\fIDefinicja klasy \fBKarta\fP\&. \fP"
.ti -1c
.RI "plik \fBtalia\&.h\fP"
.br
.RI "\fIDefinicja klasy \fBTalia\fP\&. \fP"
.ti -1c
.RI "plik \fBzestaw\&.h\fP"
.br
.RI "\fIDefinicja klasy \fBZestaw\fP\&. \fP"
.in -1c
