.TH "Dokumentacja katalogu /home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu /home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj \- 
.SH SYNOPSIS
.br
.PP
.SS "Katalogi"

.in +1c
.ti -1c
.RI "katalog \fBinc\fP"
.br
.ti -1c
.RI "katalog \fBsrc\fP"
.br
.in -1c
