.TH "/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src/interfejs.cpp" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src/interfejs.cpp \- 
.PP
Definicja metody klasy \fBInterfejs\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'interfejs\&.h'\fP
.br

.SH "Opis szczegółowy"
.PP 
Zawiera definicje metod klasy \fBInterfejs\fP\&. 
.PP
Definicja w pliku \fBinterfejs\&.cpp\fP\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
