.TH "/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/inc/interfejs.h" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/inc/interfejs.h \- 
.PP
Definicja klasy \fBInterfejs\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'talia\&.h'\fP
.br
\fC#include 'CPU\&.h'\fP
.br
\fC#include 'GRA\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBInterfejs\fP"
.br
.RI "\fIModeluje pojecie \fBInterfejs\fP\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
Plik zawiera definicje klasy \fBInterfejs\fP, ktora jest klasa pochodna i jest ona specjalizacja klasy talia, \fBCPU\fP , \fBGRA\fP\&. 
.PP
Definicja w pliku \fBinterfejs\&.h\fP\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
