.TH "/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src/karta.cpp" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src/karta.cpp \- 
.PP
Definicja metody klasy \fBKarta\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'karta\&.h'\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &Ekran, \fBKarta\fP k)"
.br
.RI "\fIPrzeciazenie operatora wyjscia\&. \fP"
.ti -1c
.RI "void \fBPrzepisz\fP (\fBKarta\fP &k1, \fBKarta\fP k2)"
.br
.RI "\fIMetoda przepisuje kolor i figure jednej z kart na druga\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
Zawiera definicje metod klasy \fBKarta\fP\&. 
.PP
Definicja w pliku \fBkarta\&.cpp\fP\&.
.SH "Dokumentacja funkcji"
.PP 
.SS "ostream& operator<< (ostream &Ekran, \fBKarta\fPk)"

.PP
Definicja w linii 46 pliku karta\&.cpp\&.
.SS "void Przepisz (\fBKarta\fP &k1, \fBKarta\fPk2)"

.PP
Definicja w linii 336 pliku karta\&.cpp\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
