.TH "/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src/main.cpp" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src/main.cpp \- 
.PP
Plik glowny programu\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'interfejs\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "int main ()"

.PP
Definicja w linii 21 pliku main\&.cpp\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
