.TH "/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/inc/talia.h" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/inc/talia.h \- 
.PP
Definicja klasy \fBTalia\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'karta\&.h'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBTalia\fP"
.br
.RI "\fIModeluje pojecie \fBTalia\fP\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
Plik zawiera definicje klasy \fBTalia\fP ktora jest klasa specjalistyczna i korzysta z klasy \fBKarta\fP\&. 
.PP
Definicja w pliku \fBtalia\&.h\fP\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
