.TH "/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src/zestaw.cpp" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/src/zestaw.cpp \- 
.PP
Definicja metody klasy \fBZestaw\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'zestaw\&.h'\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &Ekran, \fBZestaw\fP z)"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Zawiera definicje metod klasy \fBZestaw\fP\&. 
.PP
Definicja w pliku \fBzestaw\&.cpp\fP\&.
.SH "Dokumentacja funkcji"
.PP 
.SS "ostream& operator<< (ostream &Ekran, \fBZestaw\fPz)"

.PP
Definicja w linii 17 pliku zestaw\&.cpp\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
