.TH "/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/inc/zestaw.h" 3 "Śr, 11 cze 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/Project41Poker(1)/Project41Poker/Project41Poker/prj/inc/zestaw.h \- 
.PP
Definicja klasy \fBZestaw\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'karta\&.h'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBZestaw\fP"
.br
.RI "\fIModeluje pojecie \fBZestaw\fP\&. \fP"
.in -1c
.SS "Funkcje"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &Ekran, \fBZestaw\fP z)"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Plik zawiera definicje klasy \fBZestaw\fP, ktora jest klasa pochodna i jest ona specjalizacja klasy \fBKarta\fP\&. 
.PP
Definicja w pliku \fBzestaw\&.h\fP\&.
.SH "Dokumentacja funkcji"
.PP 
.SS "ostream& operator<< (ostream &Ekran, \fBZestaw\fPz)"

.PP
Definicja w linii 17 pliku zestaw\&.cpp\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
